CREATE DATABASE `dbEcole` /*!40100 COLLATE 'utf8mb4_0900_ai_ci' */;
USE `dbecole`;

CREATE TABLE `etudiant` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nom` VARCHAR(50) NULL DEFAULT NULL,
	`prenom` VARCHAR(50) NULL DEFAULT NULL,
	`age` INT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
	) COLLATE='utf8mb4_0900_ai_ci' 	ENGINE=InnoDB ;
	
